### PR TITLE
fix(sidekick): attaches .html too eagerly

### LINKED ISSUE #698: Sidekick: preview attaches .html extension to urls ending in /
Reproduce:
1. Go to https://blog.adobe.com/jp/
2. Ope the Sidekick and click preview
3. You will end up on https://master--theblog--adobe.hlx.page/jp/.html (403)

### PR DESCRIPTION
**Pull request by rofe**
Fix #698

### CODE REVIEW

File: tools/sidekick/config.js [hunk 1]
```diff
@@ -213,7 +213,8 @@
     if (!webPath) {
       return;
     }
-    if (!webPath.split('/').pop().includes('.')) {
+    const file = webPath.split('/').pop();
+    if (file && !file.includes('.')) {
```
Comment (dominique-pfister) [inline tools/sidekick/config.js:217]: I don't see the difference here: to me, both variants get the last `/` segment and add `.html` if that segment has no extension. The new version additionally checks whether the last segment is non-empty (so it wouldn't add `.html` to e.g. `/my-path//`).

Since you only want to check a `.` in the *last* segment, what about:
```
const pathSep = webPath.lastIndexOf('/');
if (pathSep !== -1 && webPath.indexOf('.', pathSep + 1) === -1( {
   // no extension
  sk.status.webPath = `${webPath}.html`;
}
```
This would avoid creating the array.

Comment (dominique-pfister) [reply tools/sidekick/config.js:217]: Ah, yes, now I see the difference 🙂

Comment (dominique-pfister) [reply tools/sidekick/config.js:217]: Changed the suggested code to include the case where the last segment is empty!

**Review by dominique-pfister — APPROVED** [review]
